/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. 
//It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4019bd84-b9e4-47b0-8d53-d7aa82967fa6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RbxOzu5G6",
    "aws_user_pools_web_client_id": "7vm7j40cgoihsoq658690qb33p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://72ul4kbdkfc2fjz544cilw3swe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ndnxtxue6ndyfhaylzgnxlouge",
    "aws_user_files_s3_bucket": "bucketunico230607-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
